Add a WM_WINDOW_ROLE property to toplevel X11 windows.
audacious-media-player/audacious-plugins pull request #134
Opened 2023-03-31 18:45 UTC by gijsbers

With window managers like icewm and i3 users can configure window specific settings. For this to work toplevel windows must be distinguishable by a X11 property. Because Audacious uses the same WM_CLASS property for all its windows, the WM_WINDOW_ROLE property must be set. However, Audacious currently does not set this property. It is defined in the ICCCM manual for X11 clients. This patch sets this property on Gtk and Qt toplevel windows using designated library calls.

2023-04-01 17:06 UTC, jlindgren90 reviewed
Some of the window roles don't seem correct; see individual comments.

Also it looks like both `skins` and `skins-qt` are missing calls to set the window role for the main window.

2023-04-01 17:06 UTC, jlindgren90 commented on src/skins-qt/playlistwin.cc
> +    playlistwin->setWindowRole ("editor");
`playlist` would be better than `editor` IMO.

2023-04-01 17:06 UTC, jlindgren90 commented on src/skins/playlistwin.cc
> +    playlistwin->setWindowRole ("editor");
`playlist` here too.

2023-04-01 17:06 UTC, jlindgren90 commented on src/skins/window.cc
> +    gtk_window_set_role ((GtkWindow *) window, "skin");
The role should be set by the subclasses (`mainwindow` or `playlist` or `equalizer`) rather than by the base class.

2023-04-01 17:38 UTC, radioactiveman commented on src/gtkui/ui_gtk.cc
> +    gtk_window_set_role ((GtkWindow *) window, "mainwindow");
This looks out of place here. Why not move it to line 801 where `window` is initialized?

2023-04-07 20:14 UTC, jlindgren90 requested changes
Still looks like both `skins` and `skins-qt` are missing calls to set the window role for the main window.

2023-04-07 20:14 UTC, jlindgren90 commented on src/amidiplug/i_fileinfo.cc
> +    gtk_window_set_role (GTK_WINDOW (fileinfowin), "fileinfo");
It looks like `gtk_window_set_role()` is called twice for the same window (here and line 155).

2023-04-07 20:14 UTC, jlindgren90 commented on src/skins/window.cc
> +    gtk_window_set_role ((GtkWindow *) window, "skin");
This still needs to be fixed.

2023-04-14 22:12 UTC, merged

2023-04-14 22:12 UTC, jlindgren90 commented
Thanks!